addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "4.0.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"         % "0.4.2")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.0.2")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.3.25")
